version: '3'
services:
  couchdb:
    container_name: safran-db
    image: couchdb:latest 
    environment:
      COUCHDB_USER: adm
      COUCHDB_PASSWORD: pass
    ports:
      - "5984:5984"
    volumes:
      - ./data:/opt/couchdb/data
volumes:
  data:
